@startuml
set namespaceSeparator ::

class "flutter_assignment2::favorites_page.dart::FavoritesPage" {
  +State<FavoritesPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::favorites_page.dart::FavoritesPage"

class "flutter_assignment2::favorites_page.dart::_FavoritesPageState" {   
  +Widget customSearchBar
  +Widget build()
}

"flutter_assignment2::favorites_page.dart::_FavoritesPageState" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::favorites_page.dart::_FavoritesPageState"

class "flutter_assignment2::home_page.dart::MyHomePage" {
  +State<MyHomePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::home_page.dart::MyHomePage"

class "flutter_assignment2::home_page.dart::_MyHomePageState" {
  +Icon customIcon
  +Widget customSearchBar
  +Widget build()
}

"flutter_assignment2::home_page.dart::_MyHomePageState" o-- "flutter::src::widgets::icon.dart::Icon"
"flutter_assignment2::home_page.dart::_MyHomePageState" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::home_page.dart::_MyHomePageState"

class "flutter_assignment2::login_page.dart::LoginPage" {
  +State<LoginPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::login_page.dart::LoginPage"

class "flutter_assignment2::login_page.dart::_LoginPage" {
  +TextEditingController myControllerUsername
  +TextEditingController myControllerPassword
  +void validateLogin()
  +Widget build()
}

"flutter_assignment2::login_page.dart::_LoginPage" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::login_page.dart::_LoginPage"

class "flutter_assignment2::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "flutter_assignment2::main.dart::MyApp"

class "flutter_assignment2::main.dart::LogoPage" {
  +String title
  +State<LogoPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::main.dart::LogoPage"

class "flutter_assignment2::main.dart::_LogoPage" {
  +void initState()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::main.dart::_LogoPage"

class "flutter_assignment2::message.dart::Message" {
  +String imageOfOffer
  +String imageOfSolicitor
  +String solicitorName
  +String offerId
  +void acceptOffer()
  +void declineOffer()
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "flutter_assignment2::message.dart::Message"

class "flutter_assignment2::messages_page.dart::MessagesPage" {
  +State<MessagesPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::messages_page.dart::MessagesPage"

class "flutter_assignment2::messages_page.dart::_MessagesPage" {
  +Map<String, dynamic> userDetails
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::messages_page.dart::_MessagesPage"

class "flutter_assignment2::my_offers.dart::MyOffers" {
  +State<MyOffers> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::my_offers.dart::MyOffers"

class "flutter_assignment2::my_offers.dart::_MyOffers" {
  +Map<String, dynamic> userDetails
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::my_offers.dart::_MyOffers"

class "flutter_assignment2::offer.dart::Offer" {
  +String id
  +String categoryId
  +String userId
  +String title
  +String description
  +String image
  +bool closed
  +String endDate
  +String createdAt
  +String closedAt
  +String distance
  +Map<String, dynamic> offerDetailsMap
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "flutter_assignment2::offer.dart::Offer"

@enduml