@startuml
set namespaceSeparator ::

class "flutter_assignment2::offer_details.dart::OfferDetails" {
  +Map<String, dynamic> offerDetailsMap
  +State<OfferDetails> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::offer_details.dart::OfferDetails"

class "flutter_assignment2::offer_details.dart::_OfferDetails" {
  +Map<String, dynamic> offerDetails
  +String title
  +String best_before
  +String distance
  +String image
  +String city
  +String description
  +bool reserved
  +void reserve()
  +void cancelReservation()
  +void checkIfReserved()
  -Future<void> _showReservationConfirmationDialog()
  -Future<void> _showAnimationOfReservationDialog()
  +Widget navBar()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::offer_details.dart::_OfferDetails"

class "flutter_assignment2::post_offer.dart::PostOffer" {
  +State<PostOffer> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::post_offer.dart::PostOffer"

class "flutter_assignment2::post_offer.dart::_PostOffer" {
  +TextEditingController myControllerName
  +TextEditingController myControllerDescription
  +TextEditingController myControllerDate
  +DateTime? newDate
  +String image1
  +String image2
  +String image3
  +String image4
  +void validateOffer()
  -Future<void> _showErrorInDateFormat()
  +Widget pictureButton()
  +Widget imageContainer()
  +Future<void> datePicker()
  +Widget build()
}

"flutter_assignment2::post_offer.dart::_PostOffer" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::post_offer.dart::_PostOffer"

class "flutter_assignment2::profile_page.dart::ProfilePage" {
  +State<ProfilePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::profile_page.dart::ProfilePage"

class "flutter_assignment2::profile_page.dart::_ProfilePage" {
  +Map<String, dynamic> userDetails
  +List<Map<String, dynamic>> friends
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::profile_page.dart::_ProfilePage"

class "flutter_assignment2::register_page.dart::RegisterPage" {
  +State<RegisterPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::register_page.dart::RegisterPage"

class "flutter_assignment2::register_page.dart::_RegisterPage" {
  +TextEditingController myControllerUsername
  +TextEditingController myControllerPassword
  +TextEditingController myControllerPassword2
  +Widget build()
}

"flutter_assignment2::register_page.dart::_RegisterPage" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::register_page.dart::_RegisterPage"

class "flutter_assignment2::take_picture.dart::TakePictureScreen" {       
  +CameraDescription camera
  +TakePictureScreenState createState()
}

"flutter_assignment2::take_picture.dart::TakePictureScreen" o-- "camera_platform_interface::src::types::camera_description.dart::CameraDescription" 
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "flutter_assignment2::take_picture.dart::TakePictureScreen"

class "flutter_assignment2::take_picture.dart::TakePictureScreenState" {  
  -CameraController _controller
  -Future<void> _initializeControllerFuture
  +void initState()
  +void dispose()
  +Widget build()
}

"flutter_assignment2::take_picture.dart::TakePictureScreenState" o-- "camera::src::camera_controller.dart::CameraController"
"flutter::src::widgets::framework.dart::State" <|-- "flutter_assignment2::take_picture.dart::TakePictureScreenState"

class "flutter_assignment2::take_picture.dart::DisplayPictureScreen" {    
  +String imagePath
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "flutter_assignment2::take_picture.dart::DisplayPictureScreen"


@enduml
